### ISSUE TITLE
Alembic files

### ISSUE THREAD

**Issue by andybak** [keijiro/DepthCamFx#3]
They are missing from the repo - I presume due to size. Is there any chance of adding a smaller proxy version so we can see what the second example scene is meant to look like?

**Comment by keijiro** [comment]
They're not added to the repository because they contain third party assets that can't be shared publicly. I'm thinking of replacing them with [Depthkit](https://www.depthkit.tv/), then I can easily provide some free examples.

**Comment by keijiro** [comment]
I'm closing this issue. Please feel free to reopen for further questions.
